apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xqok00vyj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xqok00vyj-python 
  name: xqok00vyj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xqok00vyj-python 
